### ISSUE TITLE
Not standard csv file

### ISSUE THREAD

**Issue by Lukasss93** [Lukasss93/laravel-larex#2]
The current csv delimiter is ";" instead of ",".
It's necessary to change it to support standard csv files provided by external programs like google sheets, etc...

**Comment by Lukasss93** [comment]
Fix in the next major version: v2

**Comment by Lukasss93** [comment]
Fixed in https://github.com/Lukasss93/laravel-larex/releases/tag/v2.0

**Comment by rabol** [comment]
to be honest, I think this is not 100% correct the delimiter is based on the users locale
Common Delimiters for Locales
US (United States): The standard delimiter is a comma ,.
Denmark: The standard delimiter is a semicolon ;.

**Comment by Lukasss93** [comment]
> to be honest, I think this is not 100% correct the delimiter is based on the users locale Common Delimiters for Locales US (United States): The standard delimiter is a comma ,. Denmark: The standard delimiter is a semicolon ;.

See this: https://github.com/Lukasss93/laravel-larex/discussions/43#discussioncomment-10205029
